import { AIState } from '../../utils/Types';

export { AIState };

// AI behavior constants
export const AI_CONSTANTS = {
  PATROL_ENGAGE_DISTANCE: 250,
  CHASE_DISTANCE: 300,
  ENGAGE_CIRCLE_RADIUS: 150,
  EVADE_SAFE_DISTANCE: 150,
  CHASE_TOO_CLOSE_DISTANCE: 30,
  COLLISION_AVOIDANCE_DISTANCE: 30,
  MIN_ALTITUDE: 10,
  MAX_ALTITUDE: 180,
  SMOOTH_TURN_FACTOR: 0.03,
  ROTATION_SLERP_FACTOR: 0.08,
  SHOOT_COOLDOWN: 2000, // 2 seconds
  SHOOT_MIN_DISTANCE: 20,
  SHOOT_MAX_DISTANCE: 150
};
